config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  root 'pages#main'

  resources :stories, only: [:new, :create] do
    resources :likes, module: :story
    collection do
      get :search
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watspoppin</title>
    <%= csrf_meta_tags %>
    <meta name="theme-color" content="#0080ff">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsWuaHBnrTwWY63wbeTGSzWIP6MKeYz1U&libraries=places"></script>
    <link href="https://fonts.googleapis.com/css?family=Abel|Happy+Monkey" rel="stylesheet">
    <link rel="icon" sizes="192x192" href="logo.svg">
  </head>

  <body>
    <!-- Marian Serna - https://github.com/marianserna- Full Stack. Project Manager. In charge of real time functionality using the Twitter api, action cable, and google places api. Used celluloid::io for async functionality in rails. Designed site, implemented react on rails setup, developed the front end, handled images. Implemented search functionality and integration with Twitter api in all things not related to authentication. Tested front end with Jest + Enzyme + Sinon as well as part of the back end using Rspec and Factory Bot. Deployed to Heroku and set up rake tasks for db reset every 24 hours.

    Denis Sanchez - https://github.com/Dujota - Back end. In charge of user model. Worked with devise and omniauth.All Oauth API integrations. User account control and views using Devise. All Social media(Twitter and Facebook) API integration related to authentication.

    Enderson Isai - https://github.com/soni17 - Back end. In charge of stories model. Worked with Google places api for search functionality in order to create stories from within the app. -->

    <div class="alerts">
      <% if notice  %> <p class="notice"><%= notice %></p> <% end %>
      <% if alert %><p class="alert"><%= alert %></p> <% end %>
    </div>

    <nav>
      <section class="left-nav">
        <a href="<%= root_url %>">
          <img
            src="/home-icon.svg"
            alt="home icon"
            class="home-icon"
          />
          <p class="icon-text">HOME</p>
        </a>
      </section>

      <section class="middle-nav">
        <a href="<%= new_story_url %>">
          <img
            src="/pencil-icon.svg"
            alt="pencil icon"
            class="pencil-icon"
          />
          <p class="icon-text">STORY</p>
        </a>
      </section>
      <section class="right-nav">
        <% if user_signed_in? %>  <%# this is a devise method that checks if the user is signed in or not %>
          <%= link_to current_user.name, edit_user_registration_path, class: "edit" %>
          <%= link_to  "Log Out", destroy_user_session_path, method: :delete, class: "logout"%> <%# devise requires a delete http request to log out so it is controlled by this app and not another app, security feature %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: "login" %>
          <%= link_to 'Log in', new_user_session_path, class: "signup" %>
        <% end %>
      </section>
    </nav>

    <%= yield %>

    <%= javascript_pack_tag 'watspoppin-bundle' %>
  </body>
</html>